LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE		:= dt.img
LOCAL_MODULE_TAGS	:= optional eng
LOCAL_MODULE_CLASS	:= ETC
LOCAL_SRC_FILES		:= dt.img
LOCAL_MODULE_PATH	:= $(PRODUCT_OUT)
include $(BUILD_PREBUILT)